[package]
name = "scx_bpfland"
version = "1.0.3"
authors = ["Andrea Righi <andrea.righi@linux.dev>"]
edition = "2021"
description = "A vruntime-based sched_ext scheduler that prioritizes interactive workloads. https://github.com/sched-ext/scx/tree/main"
license = "GPL-2.0-only"

[dependencies]
anyhow = "1.0.65"
ctrlc = { version = "3.1", features = ["termination"] }
clap = { version = "4.1", features = ["derive", "env", "unicode", "wrap_help"] }
crossbeam = "0.8.4"
libbpf-rs = "0.24.1"
log = "0.4.17"
scx_stats = { path = "../../../rust/scx_stats", version = "1.0.3" }
scx_stats_derive = { path = "../../../rust/scx_stats/scx_stats_derive", version = "1.0.3" }
scx_utils = { path = "../../../rust/scx_utils", version = "1.0.3" }
serde = { version = "1.0", features = ["derive"] }
simplelog = "0.12"
rlimit = "0.10.1"

[build-dependencies]
scx_utils = { path = "../../../rust/scx_utils", version = "1.0.3" }

[features]
enable_backtrace = []

[lib]
path = "src/lib.rs"

[[bin]]
name = "scx_bpfland"
path = "src/main.rs"
